export const IMAGES = {
    backCard: "/shuffle-cards/images/cards/back.png",
    cards: {
        "AS": "/shuffle-cards/images/cards/AS.png",
        "2S": "/shuffle-cards/images/cards/2S.png",
        "3S": "/shuffle-cards/images/cards/3S.png",
        "4S": "/shuffle-cards/images/cards/4S.png",
        "5S": "/shuffle-cards/images/cards/5S.png",
        "6S": "/shuffle-cards/images/cards/6S.png",
        "7S": "/shuffle-cards/images/cards/7S.png",
        "8S": "/shuffle-cards/images/cards/8S.png",
        "9S": "/shuffle-cards/images/cards/9S.png",
        "10S": "/shuffle-cards/images/cards/10S.png",
        "JS": "/shuffle-cards/images/cards/JS.png",
        "QS": "/shuffle-cards/images/cards/QS.png",
        "KS": "/shuffle-cards/images/cards/KS.png",

        "AC": "/shuffle-cards/images/cards/AC.png",
        "2C": "/shuffle-cards/images/cards/2C.png",
        "3C": "/shuffle-cards/images/cards/3C.png",
        "4C": "/shuffle-cards/images/cards/4C.png",
        "5C": "/shuffle-cards/images/cards/5C.png",
        "6C": "/shuffle-cards/images/cards/6C.png",
        "7C": "/shuffle-cards/images/cards/7C.png",
        "8C": "/shuffle-cards/images/cards/8C.png",
        "9C": "/shuffle-cards/images/cards/9C.png",
        "10C": "/shuffle-cards/images/cards/10C.png",
        "JC": "/shuffle-cards/images/cards/JC.png",
        "QC": "/shuffle-cards/images/cards/QC.png",
        "KC": "/shuffle-cards/images/cards/KC.png",

        "AD": "/shuffle-cards/images/cards/AD.png",
        "2D": "/shuffle-cards/images/cards/2D.png",
        "3D": "/shuffle-cards/images/cards/3D.png",
        "4D": "/shuffle-cards/images/cards/4D.png",
        "5D": "/shuffle-cards/images/cards/5D.png",
        "6D": "/shuffle-cards/images/cards/6D.png",
        "7D": "/shuffle-cards/images/cards/7D.png",
        "8D": "/shuffle-cards/images/cards/8D.png",
        "9D": "/shuffle-cards/images/cards/9D.png",
        "10D": "/shuffle-cards/images/cards/10D.png",
        "JD": "/shuffle-cards/images/cards/JD.png",
        "QD": "/shuffle-cards/images/cards/QD.png",
        "KD": "/shuffle-cards/images/cards/KD.png",

        "AH": "/shuffle-cards/images/cards/AH.png",
        "2H": "/shuffle-cards/images/cards/2H.png",
        "3H": "/shuffle-cards/images/cards/3H.png",
        "4H": "/shuffle-cards/images/cards/4H.png",
        "5H": "/shuffle-cards/images/cards/5H.png",
        "6H": "/shuffle-cards/images/cards/6H.png",
        "7H": "/shuffle-cards/images/cards/7H.png",
        "8H": "/shuffle-cards/images/cards/8H.png",
        "9H": "/shuffle-cards/images/cards/9H.png",
        "10H": "/shuffle-cards/images/cards/10H.png",
        "JH": "/shuffle-cards/images/cards/JH.png",
        "QH": "/shuffle-cards/images/cards/QH.png",
        "KH": "/shuffle-cards/images/cards/KH.png",
    },
}
