export const IMAGES = {
    backCard: "/shuffle-cards/images/cards/back.png",
    cards: {
        "AS": "/shuffle-cards/images/cards/AS.svg",
        "2S": "/shuffle-cards/images/cards/2S.svg",
        "3S": "/shuffle-cards/images/cards/3S.svg",
        "4S": "/shuffle-cards/images/cards/4S.svg",
        "5S": "/shuffle-cards/images/cards/5S.svg",
        "6S": "/shuffle-cards/images/cards/6S.svg",
        "7S": "/shuffle-cards/images/cards/7S.svg",
        "8S": "/shuffle-cards/images/cards/8S.svg",
        "9S": "/shuffle-cards/images/cards/9S.svg",
        "10S": "/shuffle-cards/images/cards/10S.svg",
        "JS": "/shuffle-cards/images/cards/JS.svg",
        "QS": "/shuffle-cards/images/cards/QS.svg",
        "KS": "/shuffle-cards/images/cards/KS.svg",

        "AC": "/shuffle-cards/images/cards/AC.svg",
        "2C": "/shuffle-cards/images/cards/2C.svg",
        "3C": "/shuffle-cards/images/cards/3C.svg",
        "4C": "/shuffle-cards/images/cards/4C.svg",
        "5C": "/shuffle-cards/images/cards/5C.svg",
        "6C": "/shuffle-cards/images/cards/6C.svg",
        "7C": "/shuffle-cards/images/cards/7C.svg",
        "8C": "/shuffle-cards/images/cards/8C.svg",
        "9C": "/shuffle-cards/images/cards/9C.svg",
        "10C": "/shuffle-cards/images/cards/10C.svg",
        "JC": "/shuffle-cards/images/cards/JC.svg",
        "QC": "/shuffle-cards/images/cards/QC.svg",
        "KC": "/shuffle-cards/images/cards/KC.svg",

        "AD": "/shuffle-cards/images/cards/AD.svg",
        "2D": "/shuffle-cards/images/cards/2D.svg",
        "3D": "/shuffle-cards/images/cards/3D.svg",
        "4D": "/shuffle-cards/images/cards/4D.svg",
        "5D": "/shuffle-cards/images/cards/5D.svg",
        "6D": "/shuffle-cards/images/cards/6D.svg",
        "7D": "/shuffle-cards/images/cards/7D.svg",
        "8D": "/shuffle-cards/images/cards/8D.svg",
        "9D": "/shuffle-cards/images/cards/9D.svg",
        "10D": "/shuffle-cards/images/cards/10D.svg",
        "JD": "/shuffle-cards/images/cards/JD.svg",
        "QD": "/shuffle-cards/images/cards/QD.svg",
        "KD": "/shuffle-cards/images/cards/KD.svg",

        "AH": "/shuffle-cards/images/cards/AH.svg",
        "2H": "/shuffle-cards/images/cards/2H.svg",
        "3H": "/shuffle-cards/images/cards/3H.svg",
        "4H": "/shuffle-cards/images/cards/4H.svg",
        "5H": "/shuffle-cards/images/cards/5H.svg",
        "6H": "/shuffle-cards/images/cards/6H.svg",
        "7H": "/shuffle-cards/images/cards/7H.svg",
        "8H": "/shuffle-cards/images/cards/8H.svg",
        "9H": "/shuffle-cards/images/cards/9H.svg",
        "10H": "/shuffle-cards/images/cards/10H.svg",
        "JH": "/shuffle-cards/images/cards/JH.svg",
        "QH": "/shuffle-cards/images/cards/QH.svg",
        "KH": "/shuffle-cards/images/cards/KH.svg",
    },
}
